language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "0.7"
  - "0.6"

script:
 - npm test
 - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
